/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CircleProgessCard: typeof import('./src/components/CircleProgessCard.vue')['default']
    DarkMode: typeof import('./src/components/DarkMode.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./src/components/ExampleComponent.vue')['default']
    ListCard: typeof import('./src/components/ListCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
